#!/usr/bin/env bash
# Check if an argument was passed, if not display usage on stderr
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" >&2
    exit 1
fi

# Ping the IP address exactly 5 times
ping -c 5 "$1"

