#!/usr/bin/env bash
# Configure /etc/hosts to redirect localhost and facebook.com without using sed -i

hosts_content=$(sed 's/127\.0\.0\.1\([[:space:]]\+\)localhost/127.0.0.2\1localhost/g' /etc/hosts)

if echo "$hosts_content" | grep -q "facebook.com"; then
    hosts_content=$(echo "$hosts_content" | sed 's/.*facebook.com/8.8.8.8 facebook.com/g')
else
    hosts_content=$(echo -e "${hosts_content}\n8.8.8.8 facebook.com")
fi

echo "$hosts_content" > /etc/hosts
